# Generated by Django 4.2.4 on 2023-09-03 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Дата платежа')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='Сумма платежа')),
                ('payment_intent_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID намерения платежа')),
                ('payment_method_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID метода платежа')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус платежа')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждение платежа')),
                ('paid_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Оплаченный контент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
