# Generated by Django 4.2.4 on 2023-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание контента')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('published_on', models.BooleanField(default=False, verbose_name='Дата публикации')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость подписки')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]
