# Generated by Django 4.2.4 on 2023-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контенты'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_on',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
