# Generated by Django 4.2.4 on 2023-09-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_alter_blog_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Платный контент'),
        ),
    ]
